---
name: Codacy

on:
  push:
    branches:
      - "main"
    paths:
      - '!**.h'
      - '!**.cpp'
      - '!**/CMakeLists.txt'
      - '!**/CMakePresets.json'
      - '!**/.clang-tidy'
      - '!**/.clang-format'
  pull_request:
    branches:
      - "main"
    paths:
      - '!**.h'
      - '!**.cpp'
      - '!**/CMakeLists.txt'
      - '!**/CMakePresets.json'
      - '!**/.clang-tidy'
      - '!**/.clang-format'

jobs:
  codacy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
